### ISSUE TITLE
AMQPS (SSL) Support

### ISSUE THREAD

**Issue by jasonroyle** [UnionOfRAD/li3_queue#8] opened 2017-06-20 10:33 UTC
I have used this library for some time now but have recently moved our RabbitMQ servers and now wish to communicate over AMQPS. After a quick search I have found nothing relating to AMQPS, SSL or certificates in this repository and after searching the Lithium repository I didn't find anything there that helps me either. Am I missing something or does Lithium not actually have SSL networking capability? In which case this should probably be a Lithium issue.

**Comment by markwilde** [comment] 2017-06-20 12:44
Hi Jason,

This wouldn't be a Lithium issue, the issue is only with the AMQP adapter in li3_queue.

The AMQP adapter doesn't currently support the configuration params for SSL but could be updated quite easily from doing a bit of digging.

Looks like SSL support was added to the AMQP library for PHP at version 1.8.0 (https://pecl.php.net/package-info.php?package=amqp&version=1.8.0)

Looking through the comparison: https://github.com/pdezwart/php-amqp/compare/v1.7.1...v1.8.0#diff-89309d5b78d7c1a44970257f5ec91eb6R381

It looks like some extra connection params are needed:

`typedef struct _amqp_connection_params {
 @@ -45,10 +49,15 @@ typedef struct _amqp_connection_params {
   double read_timeout;
   double write_timeout;
   double connect_timeout;
+  char *cacert;
+  char *cert;
+  char *key;
+  int verify;
 } amqp_connection_params;`

Ones required look to be cacert, cert, key, verify.

So providing you have an up to date AMQP library installed and updated https://github.com/UnionOfRAD/li3_queue/blob/master/extensions/adapter/queue/AMQP.php#L41 to include the new params to pass on to the connection, it looks like this functionality could be added quite easily.

You would need to update the __construct and the connect methods (__construct for defaults, connect to pass them on). From there it should just be updating your queue config!

Feel free to do a pull request if you implement this functionality.

**Comment by jasonroyle** [comment] 2017-06-21 11:29
Cheers Mark,

I forgot about the AMQP library and presumed Lithium's network features were being used. Thanks for the pointers, I've started to do some server upgrades as we are running an old version of the library at the moment. I'll submit a pull request soon.

**Comment by jasonroyle** [comment] 2017-06-22 16:38
Please see my pull request (#9).

Added the following AMQP queue configuration options:

- `cacert` (default `null`)
- `cert` (default `null`)
- `key` (default `null`)
- `verify` (default `true`)

For RabbitMQ configurations that have `verify` set to `verify_peer` all options are required, if `verify` is set to `verify_none` only the `cacert` option is required.

This is not a breaking change, any existing configurations should still work without these options.

*Note: The default port for AMQPS is `5671`, this library's default port is `5672`.*

**Comment by markwilde** [comment] 2017-07-03 12:55
Thanks for this, i've merged.

**Closed by markwilde** 2017-07-03 12:55 UTC
Labels: enhancement
